# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_actions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user_actions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import input_output_messages_pb2 as input__output__messages__pb2
import user_login_pb2 as user__login__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_actions.proto\x12\ruser_settings\x1a\x1binput_output_messages.proto\x1a\x10user_login.proto\"2\n\x1dGetBasicAccountDetailsRequest\x12\x11\n\tuser_uuid\x18\x01 \x01(\t\"n\n\x1b\x42\x61sicAccountDetailsResponse\x12+\n\x06status\x18\x01 \x01(\x0b\x32\x1b.input_output.HTTP_Response\x12\"\n\x04user\x18\x02 \x01(\x0b\x32\x14.user_login.UserData\"k\n\x16UpdateUserEmailRequest\x12\x14\n\x0csession_uuid\x18\x01 \x01(\t\x12\x11\n\tuser_uuid\x18\x02 \x01(\t\x12\x15\n\rcurrent_email\x18\x03 \x01(\t\x12\x11\n\tnew_email\x18\x04 \x01(\t\"m\n\x19UpdateUserPasswordRequest\x12\x11\n\tuser_uuid\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x18\n\x10\x63urrent_password\x18\x03 \x01(\t\x12\x14\n\x0cnew_password\x18\x04 \x01(\t\"\x8a\x01\n\x18UpdateUserDetailsRequest\x12\x11\n\tuser_uuid\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x0e\n\x06gender\x18\x05 \x01(\t\x12\x15\n\rdate_of_birth\x18\x06 \x01(\t\"8\n\x14\x44\x65leteAccountRequest\x12\x11\n\tuser_uuid\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t2\x80\x04\n\x13UserSettingsService\x12q\n\x13GetBasicAccountData\x12,.user_settings.GetBasicAccountDetailsRequest\x1a*.user_settings.BasicAccountDetailsResponse\"\x00\x12V\n\x0fUpdateUserEmail\x12%.user_settings.UpdateUserEmailRequest\x1a\x1a.input_output.OTP_Response\"\x00\x12]\n\x12UpdateUserPassword\x12(.user_settings.UpdateUserPasswordRequest\x1a\x1b.input_output.HTTP_Response\"\x00\x12j\n\x11UpdateUserDetails\x12\'.user_settings.UpdateUserDetailsRequest\x1a*.user_settings.BasicAccountDetailsResponse\"\x00\x12S\n\rDeleteAccount\x12#.user_settings.DeleteAccountRequest\x1a\x1b.input_output.HTTP_Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_actions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBASICACCOUNTDETAILSREQUEST']._serialized_start=84
  _globals['_GETBASICACCOUNTDETAILSREQUEST']._serialized_end=134
  _globals['_BASICACCOUNTDETAILSRESPONSE']._serialized_start=136
  _globals['_BASICACCOUNTDETAILSRESPONSE']._serialized_end=246
  _globals['_UPDATEUSEREMAILREQUEST']._serialized_start=248
  _globals['_UPDATEUSEREMAILREQUEST']._serialized_end=355
  _globals['_UPDATEUSERPASSWORDREQUEST']._serialized_start=357
  _globals['_UPDATEUSERPASSWORDREQUEST']._serialized_end=466
  _globals['_UPDATEUSERDETAILSREQUEST']._serialized_start=469
  _globals['_UPDATEUSERDETAILSREQUEST']._serialized_end=607
  _globals['_DELETEACCOUNTREQUEST']._serialized_start=609
  _globals['_DELETEACCOUNTREQUEST']._serialized_end=665
  _globals['_USERSETTINGSSERVICE']._serialized_start=668
  _globals['_USERSETTINGSSERVICE']._serialized_end=1180
# @@protoc_insertion_point(module_scope)
